target_pools:
  training:
    path: ~/Documents/rv_pools/train
    labels: [train, wiki]
    wiki:
      default_limit: 2000
      queries:
        - query: animal
        - query: building
        - query: landscape
        - query: vehicle
        - query: portrait
        - query: sculpture
        - query: painting
        - query: object
        - query: artifact
        - query: tool
        - query: music
        - query: food
        - query: statue
        - query: historical
        - query: event
  personal:
    path: ~/Documents/rv_pools/personal_pool
    labels: [me]
